[2025-02-26 10:39:24,154: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:39:24,161: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:39:24,165: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:39:24,168: INFO: common: created directory at: artifacts]
[2025-02-26 10:39:24,171: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:39:26,396: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:39:26,517: ERROR: data_ingestion: Downloaded file is not a valid ZIP file.]
[2025-02-26 10:39:26,519: ERROR: main: Failed to execute data_ingestion pipeline]
[2025-02-26 10:39:26,520: ERROR: main: Downloaded file is not a ZIP file]
[2025-02-26 10:39:26,521: INFO: main: Logging is done]
[2025-02-26 10:42:47,950: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:42:47,956: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:42:47,959: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:42:47,961: INFO: common: created directory at: artifacts]
[2025-02-26 10:42:47,962: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:42:47,963: INFO: data_ingestion: File already exists at artifacts/data_ingestion/data.zip]
[2025-02-26 10:42:47,968: ERROR: data_ingestion: Downloaded file is not a valid ZIP file.]
[2025-02-26 10:42:47,969: ERROR: main: Failed to execute data_ingestion pipeline]
[2025-02-26 10:42:47,970: ERROR: main: Downloaded file is not a ZIP file]
[2025-02-26 10:42:47,970: INFO: main: Logging is done]
[2025-02-26 10:47:58,173: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:47:58,179: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:47:58,183: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:47:58,185: INFO: common: created directory at: artifacts]
[2025-02-26 10:47:58,188: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:48:03,209: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:48:03,723: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 10:48:03,724: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 10:48:03,725: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 10:48:03,726: INFO: main: Logging is done]
[2025-02-26 10:48:23,591: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:48:23,597: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:48:23,601: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:48:23,603: INFO: common: created directory at: artifacts]
[2025-02-26 10:48:23,605: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:48:28,276: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:48:28,656: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 10:48:28,657: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 10:48:28,658: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 10:48:28,659: INFO: main: Logging is done]
